This notebook uses the [GapMinder data set](https://www.gapminder.org)

In [1]:
import pandas as pd
data = pd.read_csv("data/gapminder.tsv", sep='\t')
data.head() # show five entries

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

Using multi-indexing, answer the following questions
- Select data about countries in Asia 
- Select data about countries in Asia in years 1952 to 2000
- What is the average `pop` of countries in Asia in years 1952 to 2000

In [9]:
data.set_index('continent')

               country  year  lifeExp       pop    gdpPercap
continent
Asia       Afghanistan  1952   28.801   8425333   779.445314
Asia       Afghanistan  1957   30.332   9240934   820.853030
Asia       Afghanistan  1962   31.997  10267083   853.100710
Asia       Afghanistan  1967   34.020  11537966   836.197138
Asia       Afghanistan  1972   36.088  13079460   739.981106
Asia       Afghanistan  1977   38.438  14880372   786.113360
Asia       Afghanistan  1982   39.854  12881816   978.011439
Asia       Afghanistan  1987   40.822  13867957   852.395945
Asia       Afghanistan  1992   41.674  16317921   649.341395
Asia       Afghanistan  1997   41.763  22227415   635.341351
Asia       Afghanistan  2002   42.129  25268405   726.734055
Asia       Afghanistan  2007   43.828  31889923   974.580338
Europe         Albania  1952   55.230   1282697  1601.056136
Europe         Albania  1957   59.280   1476505  1942.284244
Europe         Albania  1962   64.820   1728137  2312.888958
Europe         Albania  1967   66.220   1984060  2760.196931
Europe         Albania  1972   67.690   2263554  3313.422188
Europe         Albania  1977   68.930   2509048  3533.003910
Europe         Albania  1982   70.420   2780097  3630.880722
Europe         Albania  1987   72.000   3075321  3738.932735
Europe         Albania  1992   71.581   3326498  2497.437901
Europe         Albania  1997   72.950   3428038  3193.054604
Europe         Albania  2002   75.651   3508512  4604.211737
Europe         Albania  2007   76.423   3600523  5937.029526
Africa         Algeria  1952   43.077   9279525  2449.008185
Africa         Algeria  1957   45.685  10270856  3013.976023
Africa         Algeria  1962   48.303  11000948  2550.816880
Africa         Algeria  1967   51.407  12760499  3246.991771
Africa         Algeria  1972   54.518  14760787  4182.663766
Africa         Algeria  1977   58.014  17152804  4910.416756
...                ...   ...      ...       ...          ...
Asia       Yemen, Rep.  1982   49.113   9657618  1977.557010
Asia       Yemen, Rep.  1987   52.922  11219340  1971.741538
Asia       Yemen, Rep.  1992   55.599  13367997  1879.496673
Asia       Yemen, Rep.  1997   58.020  15826497  2117.484526
Asia       Yemen, Rep.  2002   60.308  18701257  2234.820827
Asia       Yemen, Rep.  2007   62.698  22211743  2280.769906
Africa          Zambia  1952   42.038   2672000  1147.388831
Africa          Zambia  1957   44.077   3016000  1311.956766
Africa          Zambia  1962   46.023   3421000  1452.725766
Africa          Zambia  1967   47.768   3900000  1777.077318
Africa          Zambia  1972   50.107   4506497  1773.498265
Africa          Zambia  1977   51.386   5216550  1588.688299
Africa          Zambia  1982   51.821   6100407  1408.678565
Africa          Zambia  1987   50.821   7272406  1213.315116
Africa          Zambia  1992   46.100   8381163  1210.884633
Africa          Zambia  1997   40.238   9417789  1071.353818
Africa          Zambia  2002   39.193  10595811  1071.613938
Africa          Zambia  2007   42.384  11746035  1271.211593
Africa        Zimbabwe  1952   48.451   3080907   406.884115
Africa        Zimbabwe  1957   50.469   3646340   518.764268
Africa        Zimbabwe  1962   52.358   4277736   527.272182
Africa        Zimbabwe  1967   53.995   4995432   569.795071
Africa        Zimbabwe  1972   55.635   5861135   799.362176
Africa        Zimbabwe  1977   57.674   6642107   685.587682
Africa        Zimbabwe  1982   60.363   7636524   788.855041
Africa        Zimbabwe  1987   62.351   9216418   706.157306
Africa        Zimbabwe  1992   60.377  10704340   693.420786
Africa        Zimbabwe  1997   46.809  11404948   792.449960
Africa        Zimbabwe  2002   39.989  11926563   672.038623
Africa        Zimbabwe  2007   43.487  12311143   469.709298

[1704 rows x 5 columns]

In [11]:
data.loc['Asia']

TypeError: cannot do positional indexing on <class 'pandas.core.indexes.range.RangeIndex'> with these indexers [Asia] of <class 'str'>